version: 2
updates:
# Maintain dependencies for GitHub Actions.
# This will only update files inside .github/workflows, so we can only use this
# as a notifier for us to manually update the action.yml file.
# https://github.com/dependabot/dependabot-core/issues/4178
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
